apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foo-secret
  namespace: sealed-secrets
spec:
  encryptedData:
    foo: AgAu4r1W1turXJBFlKNqyZX8iCZNaumwz55Lsdvs7QG5K4ipFzm+2VLR36ocP1G9VDEqh0m+mj2Qv8iIhPlrA4Nrt704RvIsNvt9kIrvyaY3YN6vwftnEc9J2hEdThwX23EHR6XNa24a2HxbMXy8bCkwUgJcNg2WCfp0BtEQjV2Ovz0eUobgoHUjk3nuqR11xbIrEx2buUhr0enWKI2gHsIBzGBBq/an2bI67O0iBceCxwLFSp2QJ0vBd5JwEk6OOmBRv78VRLn4yDRwgtQw2n10D46swz6Z/HqxLdWdhLrpSPpakfCJ8GmOvRgo+K+4yFRYOjsaq4gpF28eATS7bpR96uyZCb5qU19/TxFx7/nD1naw5lFloJzPG+sW18sQmNLi7iUEKCSDHXuRvHz+P/8zIcy3PUBepmgGkuZ+uqzOKjkGPjFvVTZsvhGxGBr3bjpqG5i+SZ8BCRI2ZXQ8f2npzobGQpKExcnIvg1116FMlgaiD2ZCtkiQ2CkQJrrF86n81mkSF6b3WRhs6iPWf3BD5RuUAQgcLublH4hCqmayM9/bhwLNcYUCj+0EM7jMN4d4DuJfsNj4p8ygMvpHEDmx9trD6SIFXVn2h851b0WpYyyNF88NzFac16SThEJocMx1TBORGjLfmGtq7FEpfkZKGxoGPBdAEr7PIRsHWaPu0AGFnGVErZNzdXs0P4sgBkLIQ5c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: foo-secret
      namespace: sealed-secrets

