apiVersion: ENC[AES256_GCM,data:S5c=,iv:j+WVd/teCDzNJFNt/yFpt4lzpv4IoRD1HkePnioyrR0=,tag:vxXzb9FEudXRJgUTcIqyBA==,type:str]
stringData:
    foo: ENC[AES256_GCM,data:sBc5,iv:G4joPoQrwB0DkjqHtRCLCPKfrJ6MoCajoc3FPw8MsfY=,tag:z73iGYzdGjc0sd/VCGTzuA==,type:str]
kind: ENC[AES256_GCM,data:Ym+QKQdd,iv:21+5HBABwA90alsK+o/KZ0Qf2wquH/xrhsdM5vn+0eM=,tag:5gr8gP6jxfyBj8+awG/P8Q==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:jhiY,iv:5bUaVPvEAp8S2kx+093bYYZNZuFshU+ecKtLPBFNo+U=,tag:GkKIQoJboJdkbyQrSpOQGw==,type:str]
    namespace: ENC[AES256_GCM,data:QSjtOynME9PSaZhgoBg=,iv:CTOqbzloqgJ6e8pn079zIEfbNIAx5WQ1Vs9LmjrmWkE=,tag:TF75B2k0036OyHh+ss03oQ==,type:str]
type: ENC[AES256_GCM,data:G7+0Ky90,iv:3pmxuoDg76dvDofnmgpoDiGGf47eM0UyDzgUbJIUafY=,tag:DxJzyuNalcVBFvLJ+M8ntg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-23T09:43:21Z"
    mac: ENC[AES256_GCM,data:O2ndT2Vu3ZNExvE0jykPjaI5CiMX86YKHDknXewxgkHxoARrbdmnlwWGhZP3Wscair3yv1WCDILVtP48AA8LNSVe1vcMbvV7bvClmJNg11NTxRfmrxsMbN7tSvNJ8kj8+VfLO6akRH+FSsmnXVXRfASq7Mrr2KUJr2li3J9M5l8=,iv:2lF/yk/FcXZugO4jSopTY7t14G7h47YLhsE3ET6Jtp4=,tag:HXHW7k1ohwK7riBQdOApWA==,type:str]
    pgp:
        - created_at: "2022-03-23T08:57:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1FH4nk+hvMsARAAuYZ1DFbZ3NVlJnkDx0mJdmDQzeMdxlx0FU9fJt81XE8j
            NCoxKdo03MyqGkxCJNdeqEaSuxWe6QzDeKBd4m9uxBAxo2Z0tRdvGThPrtB7qva4
            ikJVpco1Vu7H85NG5fgpDlDBtXZLdZiU3TfKSUMxIYrxmNJvvkEzchBWF3rKd5eq
            CO/rz7xZw8mlBuvjzyWxy3UQZcjaYiQoCqIyVGncqbaDOq+zUUY0A3QauWqKXUc1
            Ypm38twWEFqZxfP8U92zK+b46pBj/a2w61FUyOItdDzW8OvZQD4Qdp9QBKL3sPbl
            Gpv17YBCNB3ebLlXitKGN5xn1lOwOi5udPfvfW0iXohLiaGe28e/7WwIIs2tNAn9
            OxpM9U8oVuM8DPN9pn8UzosNTqCqPo3b4XqbjmWXG6vUaWKH8xgrF0HbEu32CEgD
            I5iDhYDLxn7QBYSVvYHo39L+B420JITe27zt2IpoHfcha1aBtv3gziGfjxXNALFe
            BSgLjCT4M+Lx8fl/gK9+wrFyKmEVJMdnzicSY4idTgmqi6iW7Ol8P8ArjVB95Dff
            aEVdp32gMQgAjy6kW4dKGa5hlsmwyqtAe9eFjMtK6ZAR5DpkrvPJC6UK5plH6G1N
            A1GC2BMkCl/48/kEgVX8uPb9UjLfD6N1AdXCbh/YeToyQ2QmMRk9W23YCUEO9oTU
            aAEJAhATDzMEtPXA4uTJ3dk+GrUXMZEpL0F4IaBl/eshdPJOOkbzHZLS8D/hcXxh
            Ea37aozumaYI/oIwbgWR/p56eeELRFQslNkfmWGsRDh9y3PHQgVAPcmF/xYdCeHl
            lkyCub0QNjX2
            =8+ka
            -----END PGP MESSAGE-----
          fp: 2993FF2065E46521576A5FFF34181E40C6544217
    unencrypted_suffix: _unencrypted
    version: 3.7.2
