apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-taxi
  name: dev-app-taxi
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/environments/dev/apps/app-taxi/overlays
    repoURL: https://github.com/marcoklaassen/gitops-demo-1.4.3.git
  syncPolicy: null
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
